### ISSUE TITLE
Switch to @types

### ISSUE THREAD

**Issue by quantuminformation** [abauzac/nightwatch-typescript#1]
There are now official types

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19294

**Comment by abauzac** [comment]
Thanks for reporting, working on it but got some issues with types for now (merging namespace for resemblejs and merging custom assert/command with NightwatchApi/Assertions)

**Comment by quantuminformation** [comment]
thx for the update

**Comment by abauzac** [comment]
Made a PR in defintelytyped as getTitle Api was wrong https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21745

**Comment by abauzac** [comment]
This was auto-closed by commit but if you find something wrong, don't hesitate, I'll reopen it 

Edit : this fix brings some breaking changes to types. I've totally removed imports using "typings" command and only used npm @types

**Comment by quantuminformation** [comment]
thx man!
